# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ColectorGPS
                                 A QGIS plugin
 Complemento que permite la recolección de información espacial y alfanumérica en QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-03-04
        git sha              : https://github.com/AlexanderPretel/Colector
        copyright            : (C) 2021 by Alexander Pretel Díaz
        email                : alexander.pretel@correounivalle.edu.co
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import sys


def colectar_punto(ruta: str, nombre: str, tiempo: str = '30') -> int:
    sentencia = "timeout {0} str2str -in serial://ttyACM0:9600#ubx -out file://{1}{2}".format(str(tiempo), str(ruta),
                                                                                              str(nombre))
    bash = os.system(sentencia)
    return bash


if __name__ == "__main__":
    try:
        if len(sys.argv) == 4:
            locals()[sys.argv[1]](sys.argv[2], sys.argv[3])
        elif len(sys.argv) == 5:
            print(sys.argv)
            locals()[sys.argv[1]](sys.argv[2], sys.argv[3], sys.argv[4])
        else:
            print("Error al ejecutar la función")
    except:
        print(len(sys.argv))
        print("No ha sido posible ejecutar la función")
